name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]

    steps:
      - name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
      - uses: actions/checkout@v2
      
      - name: Setup Node ${{ matrix.node_version }}
      - uses: actions/setup-node@v2.1.5
        with:
          version: 14.17.3
      
      - name: Github actions for yarn
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
        
      - name: Creating build
        run: yarn build
        
      - name: Run test
        run: yarn run test
